version: 0.2

env:
  variables:
    STAGE: "prod"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase..."
      - npm ci --no-audit --no-fund || npm install --no-audit --no-fund
      - npm install -g serverless@3
      - export PATH=$(npm bin -g):$PATH

  pre_build:
    commands:
      - echo "pre_build..."
      - echo "Ensure MONGO_URI and JWT_SECRET are provided as env vars in CodeBuild/CodePipeline if needed"

  build:
    commands:
      - echo "Packaging service (no deploy)..."
      - serverless package --stage $STAGE --verbose
      - echo "Packaging finished."

artifacts:
  base-directory: .serverless
  files:
    - '**/*'
  discard-paths: no
