version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  pre_build:
    commands:
      - echo "=== Build Environment Setup ==="
      - echo "Repository structure:"
      - ls -la
      - echo "Checking serverless.yml file:"
      - cat serverless.yml
      - echo "=== End of serverless.yml ==="
      - echo "Installing all dependencies"
      - npm install
      - echo "Checking serverless version:"
      - npx serverless --version
      - echo "Validating serverless.yml syntax with detailed output:"
      - npx serverless print --stage prod --region ap-south-1 --verbose
      
  build:
    commands:
      - echo "=== Building Serverless Application ==="
      - npx serverless package --stage prod --region ap-south-1 --verbose
      
  post_build:
    commands:
      - echo "=== Build Completion ==="
      - echo "Build completed successfully"

artifacts:
  files:
    - .serverless/**/*
    - serverless.yml
  name: academic-management-backend-artifacts
