version: 0.2

env:
  variables:
    NODE_ENV: development

phases:
  pre_build:
    commands:
      - echo "=== Build Environment Setup ==="
      - echo "Repository structure:"
      - ls -la
      - echo "Navigating to backend directory"
      - if [ -d backend ]; then cd backend; else echo 'ERROR: backend directory not found. Current listing:'; ls -la; exit 1; fi
      - echo "Backend directory contents:"
      - ls -la
      - echo "Checking serverless.yml file:"
      - cat serverless.yml
      - echo "=== End of serverless.yml ==="
      - echo "Checking for hidden characters:"
      - hexdump -C serverless.yml | tail -5
      - echo "Increasing file descriptor limit"
      - ulimit -n 65536
      - echo "Installing all dependencies"
      - npm ci
      - echo "Checking serverless version:"
      - npx serverless --version
      - echo "Validating serverless.yml syntax with detailed output:"
      - npx serverless print --stage prod --region ap-south-1 --verbose
      
  build:
    commands:
      - echo "=== Building Serverless Application ==="
      - npx serverless package --stage prod --region ap-south-1 --verbose
      
  post_build:
    commands:
      - echo "=== Build Completion ==="
      - echo "Build completed successfully"
      - if [ -d .serverless ]; then
          echo "Serverless artifacts found:";
          ls -la .serverless/;
        else
          echo "ERROR: No .serverless directory found";
          exit 1;
        fi

artifacts:
  files:
    - backend/.serverless/**/*
    - backend/serverless.yml
  name: academic-management-backend-artifacts
