version: 0.2

env:
  variables:
    STAGE: "prod"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase: installing production dependencies only..."
      # install only production deps to keep node_modules small
      - npm ci --only=production --no-audit --no-fund
      - npm install -g serverless@3
      - export PATH=$(npm bin -g):$PATH

  pre_build:
    commands:
      - echo "pre_build..."
      - echo "Attempting to raise file descriptor limit (may be restricted in CI)..."
      - ulimit -n 4096 || echo "Could not raise ulimit; continuing"
      - echo "Ensure MONGO_URI and JWT_SECRET are provided as env vars in CodeBuild/CodePipeline if needed"

  build:
    commands:
      - echo "Packaging service (no deploy)..."
      - ulimit -n 4096 || echo "Could not raise ulimit before packaging; continuing"
      - serverless package --stage $STAGE --verbose
      - echo "Packaging finished."

artifacts:
  base-directory: .serverless
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**/*'
