version: 0.2

env:
  variables:
    STAGE: "prod"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Serverless..."
      - npm install -g serverless@3
      - export PATH=$(npm bin -g):$PATH

  pre_build:
    commands:
      - echo "Environment variables loaded from CodeBuild:"
      - echo "MONGO_URI and JWT_SECRET loaded (hidden)."
      - echo "Installing dependencies..."
      - npm ci --no-audit --no-fund || npm install --no-audit --no-fund

  build:
    commands:
      - echo "Deploying with Serverless..."
      - serverless deploy --stage $STAGE --verbose

  post_build:
    commands:
      - echo "Deployment finished."
      - if [ -d ".serverless" ]; then ls -la .serverless/; else echo "No .serverless directory"; fi

artifacts:
  base-directory: .serverless
  files:
    - "**/*"
  name: serverless-artifacts
  discard-paths: no
