version: 0.2

env:
  variables:
    NODE_ENV: test

phases:
  install:
    commands:
      - echo "=== Installing Dependencies ==="
      - npm install --legacy-peer-deps || npm install
      
  pre_build:
    commands:
      - echo "=== Running Tests ==="
      - npm test
      
  build:
    commands:
      - echo "=== Tests Completed ==="
      
post_build:
  on-failure: CONTINUE
  commands:
    - echo "Test phase completed"

reports:
  test-report:
    files:
      - 'test-results.json'
    file-format: 'JUNITXML'
